version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '00:00'
      timezone: 'America/Chicago' # 12am Central Time
    commit-message:
      prefix: '[DEPENDABOT]'
    labels:
      - 'dependencies'
      - 'dependabot'
    open-pull-requests-limit: 10
    reviewers:
      - 'stefcameron'
    versioning-strategy: 'increase'
    ignore:
      # ignore React 19 and related dependencies to keep tests based on R18 for now
      - dependency-name: "react"
        versions: ["19.x"]
      - dependency-name: "@types/react"
        versions: ["19.x"]
      - dependency-name: "react-dom"
        versions: ["19.x"]
      - dependency-name: "@types/react-dom"
        versions: ["19.x"]
